apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-f5vs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-taty-tenant/rhtap-demo-app/hacbs-test-project-f5vs@sha256:01a52f1a0592a88c7dd4eb548512d9f3e6a8c66f4aa53ec4fdfb76f991b1e509
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
